[env:esp32c3]
platform = espressif32 @ 6.6.0
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600


lib_deps =
    moononournation/GFX Library for Arduino @ 1.4.9
    bblanchon/ArduinoJson@^6.21.3
    https://github.com/jnthas/Improv-WiFi-Library.git

build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1

board_build.partitions = min_spiffs.csv




